language: python
python:
  - "2.7"
before_install:
- pip install --upgrade setuptools
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: "python setup.py install && python setup.py test" 
